# Basics to Intermediate NumPy Concepts with Python

Reference Video: 
https://www.youtube.com/watch?v=yAjzj2eShXU&list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK&index=5

## Numpy Array Operations Basics

You are working on a project that involves analyzing temperature data for a week. Your task is to demonstrate your understanding of Numpy array operations by performing the following steps:
1. Create a Numpy array representing daily average temperatures for a week (7 days).
2. Create a view of this array that shows the temperatures in Fahrenheit (original is in Celsius).
3. Modify the original array to reflect a temperature increase for a specific day.
4. Create a copy of the original array.
5. Make a change to the original array again.
6. Make a change to the copied array.

After each step, print the relevant arrays to show how they change. Explain the differences between views and copies in Numpy arrays based on your observations.

In [3]:
# Import necessary libraries
import numpy as np

# Create a Numpy array representing daily average temperatures for a week (7 days).
temperatures = np.array([20, 21, 22, 23, 24, 25, 26])
print("Original temperatures in Celsius:")
print(temperatures)

# Create a view of this array that shows the temperatures in Fahrenheit (original is in Celsius).
temperatures_fahrenheit = temperatures * 9 / 5 + 32
print("Temperatures in Fahrenheit:")
print(temperatures_fahrenheit)

# Modify the original array to reflect a temperature increase for a specific day.
temperatures[3] += 3
print("Updated temperatures in Celsius:")
print(temperatures)

# Create a copy of the original array.
temperatures_copy = temperatures.copy()
print("Copy of temperatures:")
print(temperatures_copy)

# Make a change to the original array again.
temperatures[5] += 2
print("Updated temperatures in Celsius:")
print(temperatures)

# Make a change to the copied array.
temperatures_copy[1] += 1
print("Updated copy of temperatures:")
print(temperatures_copy)

# Explanation:
# A view is a way of looking at the same data in a different way, without creating a new array.
# A copy is a new array that is created with the same data as the original array.
# When you modify a view, the original array is also modified.
# When you modify a copy, the original array is not modified.
# In this example, when we modified the original array, the view also changed.
# However, when we modified the copied array, the original array remained the same.
# This demonstrates the difference between views and copies in Numpy arrays.

Original temperatures in Celsius:
[20 21 22 23 24 25 26]
Temperatures in Fahrenheit:
[68.  69.8 71.6 73.4 75.2 77.  78.8]
Updated temperatures in Celsius:
[20 21 22 26 24 25 26]
Copy of temperatures:
[20 21 22 26 24 25 26]
Updated temperatures in Celsius:
[20 21 22 26 24 27 26]
Updated copy of temperatures:
[20 22 22 26 24 25 26]


## NumPy Array Operations

You are given a list of daily temperature readings for a month. Your task is to perform the following operations using NumPy:
1. Create a 1-D NumPy array from the temperature readings and print its shape.
2. Reshape the 1-D array into a 2-D array with 4 rows, representing weeks. Print the new shape.
3. Calculate and print the average temperature for each week.
4. Reshape the 2-D array into a 3-D array with dimensions (2, 2, 7), representing two bi-weekly periods. Print the new shape.
5. Calculate and print the maximum temperature for each bi-weekly period.
6. Flatten the 3-D array back to 1-D and print the result.

In [4]:
# Use the following temperature data:
temperatures = [
    25, 28, 23, 24, 27, 26, 24,  # Week 1
    22, 21, 23, 25, 26, 28, 27,  # Week 2
    26, 24, 23, 24, 25, 27, 28,  # Week 3
    29, 30, 28, 26, 25, 24, 23   # Week 4
]

# Import necessary libraries
import numpy as np

# Create a 1-D NumPy array from the temperature readings and print its shape.
temperature_array = np.array(temperatures)
print("1-D array shape:")
print(temperature_array.shape)

# Reshape the 1-D array into a 2-D array with 4 rows, representing weeks. Print the new shape.
weekly_temperatures = temperature_array.reshape(4, 7)
print("2-D array shape:")
print(weekly_temperatures.shape)

# Calculate and print the average temperature for each week.
average_temperatures = np.mean(weekly_temperatures, axis=1)
print("Average temperature for each week:")
print(average_temperatures)

# Reshape the 2-D array into a 3-D array with dimensions (2, 2, 7), representing two bi-weekly periods. Print the new shape.
biweekly_temperatures = weekly_temperatures.reshape(2, 2, 7)
print("3-D array shape:")
print(biweekly_temperatures.shape)

# Calculate and print the maximum temperature for each bi-weekly period.
max_temperatures = np.max(biweekly_temperatures, axis=(1, 2))
print("Maximum temperature for each bi-weekly period:")
print(max_temperatures)

# Flatten the 3-D array back to 1-D and print the result.
flattened_temperatures = biweekly_temperatures.flatten()
print("Flattened 1-D array:")
print(flattened_temperatures)

1-D array shape:
(28,)
2-D array shape:
(4, 7)
Average temperature for each week:
[25.28571429 24.57142857 25.28571429 26.42857143]
3-D array shape:
(2, 2, 7)
Maximum temperature for each bi-weekly period:
[28 30]
Flattened 1-D array:
[25 28 23 24 27 26 24 22 21 23 25 26 28 27 26 24 23 24 25 27 28 29 30 28
 26 25 24 23]


## NumPy Array Iteration

Given the following NumPy arrays, write functions to:
1. Calculate the sum of squares for a 1-D array
2. Find the maximum element in each row of a 2-D array
3. Calculate the product of elements along the first axis of a 3-D array
4. Use nditer() to iterate through a 3-D array and count elements greater than the mean

Use different iteration methods for each task:
- Standard iteration for 1-D array
- Nested loops for 2-D array
- Multiple nested loops for 3-D array
- nditer() for the last task

In [5]:
# Import necessary libraries
import numpy as np

# Arrays:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# Calculate the sum of squares for a 1-D array
def sum_of_squares(arr):
    sum_squares = 0
    for num in arr:
        sum_squares += num ** 2
    return sum_squares

print("Sum of squares for 1-D array:")
print(sum_of_squares(arr_1d))

# Find the maximum element in each row of a 2-D array
def max_in_each_row(arr):
    max_elements = []
    for row in arr:
        max_elements.append(np.max(row))
    return max_elements

print("Maximum element in each row of 2-D array:")
print(max_in_each_row(arr_2d))

# Calculate the product of elements along the first axis of a 3-D array
def product_along_first_axis(arr):
    product = 1
    for matrix in arr:
        product *= np.prod(matrix)
    return product

print("Product of elements along the first axis of 3-D array:")
print(product_along_first_axis(arr_3d))

# Use nditer() to iterate through a 3-D array and count elements greater than the mean
def count_elements_greater_than_mean(arr):
    count = 0
    mean = np.mean(arr)
    for element in np.nditer(arr):
        if element > mean:
            count += 1
    return count

print("Number of elements greater than the mean in 3-D array:")
print(count_elements_greater_than_mean(arr_3d))

Sum of squares for 1-D array:
55
Maximum element in each row of 2-D array:
[3, 6, 9]
Product of elements along the first axis of 3-D array:
479001600
Number of elements greater than the mean in 3-D array:
6
