# Basics of PyTorch and OOP

## Tensors
In this exercise, you'll work with PyTorch tensors to perform basic operations and practice multidimensional indexing. You'll create a 3D tensor, perform some transformations, and extract specific elements using indexing techniques.

The goal is to familiarize yourself with PyTorch's tensor operations and understand how to manipulate multidimensional data efficiently.

In [1]:
import torch

# Create a 3D tensor of size 4x3x2 filled with random integers between 0 and 9
tensor_3d = torch.randint(0, 10, (4, 3, 2))
print("Original 3D tensor:")
print(tensor_3d)

# Multiply all elements of the tensor by 2
tensor_3d_multiplied = tensor_3d * 2

# Add 5 to all elements of the tensor
tensor_3d_added = tensor_3d + 5

# Calculate the mean of the entire tensor
mean = torch.mean(tensor_3d.float())

# Extract a 2x2 sub-tensor from the last two rows and columns of the middle layer (index 1)
sub_tensor = tensor_3d[2:, 1:, :]

# Find the maximum value in each of the 4 2x3 matrices
max_values = torch.max(tensor_3d, dim=2).values

# Print your results
print("\nMultiplied tensor:")
print(tensor_3d_multiplied)
print("\nAdded tensor:")
print(tensor_3d_added)
print("\nMean of the tensor:")
print(mean)
print("\nExtracted sub-tensor:")
print(sub_tensor)
print("\nMaximum values:")
print(max_values)

Original 3D tensor:
tensor([[[1, 1],
         [3, 8],
         [0, 2]],

        [[5, 3],
         [3, 8],
         [4, 3]],

        [[7, 6],
         [6, 5],
         [8, 0]],

        [[7, 9],
         [6, 4],
         [9, 9]]])

Multiplied tensor:
tensor([[[ 2,  2],
         [ 6, 16],
         [ 0,  4]],

        [[10,  6],
         [ 6, 16],
         [ 8,  6]],

        [[14, 12],
         [12, 10],
         [16,  0]],

        [[14, 18],
         [12,  8],
         [18, 18]]])

Added tensor:
tensor([[[ 6,  6],
         [ 8, 13],
         [ 5,  7]],

        [[10,  8],
         [ 8, 13],
         [ 9,  8]],

        [[12, 11],
         [11, 10],
         [13,  5]],

        [[12, 14],
         [11,  9],
         [14, 14]]])

Mean of the tensor:
tensor(4.8750)

Extracted sub-tensor:
tensor([[[6, 5],
         [8, 0]],

        [[6, 4],
         [9, 9]]])

Maximum values:
tensor([[1, 8, 2],
        [5, 8, 4],
        [7, 6, 8],
        [9, 6, 9]])


## Broadcasting
In this exercise, you'll explore PyTorch's broadcasting capabilities, understand the differences between reshape and view operations, and learn how to transfer data between CPU and GPU.

You'll create tensors of different shapes, perform broadcasting operations, and manipulate tensor shapes. Additionally, you'll check for GPU availability and move your data to the GPU if possible.

The goal is to deepen your understanding of tensor operations and device management in PyTorch.


In [2]:
import torch

# Check if CUDA (GPU) is available and set the device accordingly
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create a 2D tensor of size 3x4
tensor_2d = torch.tensor([[1, 2, 3, 4],
                          [5, 6, 7, 8],
                          [9, 10, 11, 12]])

# Create a 1D tensor of size 4 with values [10, 20, 30, 40]
tensor_1d = torch.tensor([10, 20, 30, 40])

# Use broadcasting to add the 1D tensor to each row of the 2D tensor
broadcasted_result = tensor_2d + tensor_1d

# Reshape the 2D tensor into a 3D tensor of shape (3, 2, 2)
tensor_3d = tensor_2d.reshape(3, 2, 2)

# Use view to change the 3D tensor back to a 2D tensor of shape (3, 4)
tensor_2d_back = tensor_3d.view(3, 4)

# If CUDA is available, move the 2D tensor to GPU
tensor_2d = tensor_2d.to(device)

# Print results and tensor information
print("Original 2D tensor:")
print(tensor_2d)
print("\n1D tensor:")
print(tensor_1d)
print("\nBroadcasted addition result:")
print(broadcasted_result)
print("\nReshaped 3D tensor:")
print(tensor_3d)
print("\nViewed 2D tensor:")
print(tensor_2d_back)
print("\nTensor device:", tensor_2d.device)

Original 2D tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

1D tensor:
tensor([10, 20, 30, 40])

Broadcasted addition result:
tensor([[11, 22, 33, 44],
        [15, 26, 37, 48],
        [19, 30, 41, 52]])

Reshaped 3D tensor:
tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

Viewed 2D tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

Tensor device: cpu


# PyTorch Operations

In this exercise, you'll work with more advanced PyTorch operations and explore the relationship between PyTorch tensors and NumPy arrays. You'll use assert statements for validation, convert between NumPy and PyTorch formats, and apply various tensor manipulation techniques.

The goal is to deepen your understanding of PyTorch's capabilities and how it interacts with NumPy, while also practicing common tensor operations that are crucial for preprocessing and managing data in machine learning workflows.

In [3]:
import torch
import numpy as np

# Create a 3D NumPy array
np_array = np.random.rand(2, 3, 4)

# Convert the NumPy array to a PyTorch tensor
tensor_convert = torch.tensor(np_array)

# Use an assert statement to verify the shape of the tensor
assert tensor_convert.shape == torch.Size([2, 3, 4])

# Perform a transpose operation to swap the last two dimensions
tensor_transposed = tensor_convert.transpose(1, 2)

# Flatten the tensor to 2D (keeping the first dimension intact)
tensor_flattened = tensor_transposed.reshape(2, -1)

# Use squeeze to remove any dimensions of size 1
tensor_squeezed = tensor_flattened.squeeze()

# Use unsqueeze to add a new dimension at index 1
tensor_unsqueezed = tensor_squeezed.unsqueeze(1)

# Detach the tensor from the computation graph
tensor_detached = tensor_unsqueezed.detach()

# Convert the tensor back to a NumPy array
np_array_final = tensor_detached.numpy()

# Print results at each step
print("Original NumPy array shape:", np_array.shape)
print("PyTorch tensor shape:", tensor_convert.shape)
print("Transposed tensor shape:", tensor_transposed.shape)
print("Flattened tensor shape:", tensor_flattened.shape)
print("Squeezed tensor shape:", tensor_squeezed.shape)
print("Unsqueezed tensor shape:", tensor_unsqueezed.shape)
print("Final NumPy array shape:", np_array_final.shape)

Original NumPy array shape: (2, 3, 4)
PyTorch tensor shape: torch.Size([2, 3, 4])
Transposed tensor shape: torch.Size([2, 4, 3])
Flattened tensor shape: torch.Size([2, 12])
Squeezed tensor shape: torch.Size([2, 12])
Unsqueezed tensor shape: torch.Size([2, 1, 12])
Final NumPy array shape: (2, 1, 12)


## Object-Oriented Programming (OOP)
A programming paradigm that uses objects to structure code. In Python, everything is an object, and OOP principles are fundamental to the language. Let's explore the basics of OOP by creating a simple class.

Key concepts we'll cover:
1. Class definition
2. Attributes (instance variables)
3. Methods (instance methods)
4. Constructor (__init__ method)
5. Creating objects (instances) of a class
6. Accessing and modifying attributes
7. Calling methods

In [4]:
# Class definition for a Car object
class Car:
    def __init__(self, make, model, year, color):
        self.make = make
        self.model = model
        self.year = year
        self.color = color
        self.speed = 0

    def accelerate(self, speed_increase):
        self.speed += speed_increase
        print(f"The {self.color} {self.make} {self.model} is now going {self.speed} mph.")

    def brake(self, speed_decrease):
        if self.speed - speed_decrease < 0:
            self.speed = 0
        else:
            self.speed -= speed_decrease
        print(f"The {self.color} {self.make} {self.model} has slowed down to {self.speed} mph.")

    def paint(self, new_color):
        self.color = new_color
        print(f"The {self.make} {self.model} has been painted {self.color}.")

# Create an instance of the Car class
car = Car("Toyota", "Corolla", 2020, "red")

# Print out some attributes of your car
print(f"My car is a {car.year} {car.color} {car.make} {car.model}.")

# Use the accelerate method to increase the speed of your car
car.accelerate(50)

# Use the brake method to decrease the speed of your car
car.brake(20)

# Change the color of your car using the paint method
car.paint("blue")

My car is a 2020 red Toyota Corolla.
The red Toyota Corolla is now going 50 mph.
The red Toyota Corolla has slowed down to 30 mph.
The Toyota Corolla has been painted blue.


# Neural Network

In this exercise, you'll create a simple neural network using PyTorch's nn.Module and nn.Linear.
This will help you understand how PyTorch uses object-oriented programming to define neural network architectures.

You'll define a class for a basic feedforward neural network with two linear layers,
create an instance of this network, and then use it to make a prediction on some random input data.

The goal is to familiarize yourself with the structure of PyTorch models and how they relate to
the object-oriented programming concepts you've learned.


In [5]:
# Import necessary libraries
import torch
import torch.nn as nn

# Define a simple neural network with one linear layer
class SimpleNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SimpleNetwork, self).__init__()

        # Define the first linear layer (input_size to hidden_size)
        self.layer1 = nn.Linear(input_size, hidden_size)

        # Define the second linear layer (hidden_size to output_size)
        self.layer2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        # Implement the forward pass
        # Hint: Pass the input through layer1, then through layer2
        x = self.layer1(x)
        x = torch.relu(x)
        x = self.layer2(x)
        return x
    
# Create an instance of SimpleNetwork with input_size=3, hidden_size=4, output_size=2
model = SimpleNetwork(3, 4, 2)

# Create a random input tensor of shape (1, 3)
input_tensor = torch.rand(1, 3)

# Use your network to make a prediction with the random input
output = model(input_tensor)

# Print the network structure and the output
print("Network structure:")
print(model)
print("\nNetwork prediction:")
print(output)

Network structure:
SimpleNetwork(
  (layer1): Linear(in_features=3, out_features=4, bias=True)
  (layer2): Linear(in_features=4, out_features=2, bias=True)
)

Network prediction:
tensor([[0.3900, 0.1756]], grad_fn=<AddmmBackward0>)


## Inheritance
A fundamental concept in object-oriented programming that allows a class to inherit attributes and methods from another class. This promotes code reuse and allows for the creation of hierarchical relationships between classes.

In this exercise, you'll create a base class and a derived class to understand how inheritance works in Python.

Key concepts we'll cover:
1. Creating a base class
2. Creating a derived class that inherits from the base class
3. Overriding methods in the derived class
4. Using the super() function to call methods from the base class

In [6]:
# Create an Animal class with a constructor and two methods
class Animal:
    def __init__(self, name, species):
        self.name = name
        self.species = species

    def make_sound(self):
        print("The animal makes a sound")

    def introduce(self):
        print(f"I am {self.name}, a {self.species}")

# Create a Dog class that inherits from Animal
class Dog(Animal):
    # Override the __init__ method to include a 'breed' attribute
    def __init__(self, name, species, breed):
        super().__init__(name, species)
        self.breed = breed

    # Override the make_sound method to print "Woof!"
    def make_sound(self):
        print("Woof!")

    # Create a new method called 'fetch' that prints "[name] is fetching the ball!
    def fetch(self):
        print(f"{self.name} is fetching the ball!")

# Create an instance of the Dog class
dog = Dog("Buddy", "Dog", "Golden Retriever")

# Call the introduce method for your dog instance
dog.introduce()

# Call the make_sound method for your dog instance
dog.make_sound()

# Call the fetch method for your dog instance
dog.fetch()

I am Buddy, a Dog
Woof!
Buddy is fetching the ball!
