# NumPy with Python

Reference Videos:

https://www.youtube.com/watch?v=gnKbAAVUzro&list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK&index=1

https://www.youtube.com/watch?v=PbKOrSottRQ&list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK&index=2

https://www.youtube.com/watch?v=4LIAHVXnpbY&list=PLCC34OHNcOtpalASMlX2HHdsLNipyyhbK&index=3

In [1]:
# Import necessary libraries
import numpy as np

## NumPy Array Creation and Manipulation

- Create a NumPy array using arange() with a step of 0.5, starting from 0 and ending at 5 (exclusive).
- Then, reshape it into a 2D array with 2 rows.
- Next, create a 3x3 array of zeros and a 2x2 array filled with the value 7.
- Finally, convert the Python list [1, 2, 3, 4, 5] to a NumPy array and extract the third element.

In [14]:
# NumPy array using arange()
array = np.arange(0, 5, 0.5)
print("1D Array:", array)

# Reshape into a 2D array
reshaped_array = array.reshape(2, -1)
print("Reshaped Array (2D):", reshaped_array)

# Create a 3x3 array of zeros
zeros_array = np.zeros((3, 3))
print("3x3 Zeros Array:", zeros_array)

# Create a 2x2 array filled with the value 7
sevens_array = np.full((2, 2), 7)
print("2x2 Array filled with 7s:", sevens_array)

# Convert Python list to NumPy array
list_to_array = np.array([1, 2, 3, 4, 5])

# Extract the third element
third_elem = list_to_array[2]
print("Third element:", third_elem)

1D Array: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
Reshaped Array (2D): [[0.  0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4.  4.5]]
3x3 Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2x2 Array filled with 7s: [[7 7]
 [7 7]]
Third element: 3


## NumPy Array Slicing

- Create a 1D NumPy array containing integers from 0 to 19.
- Perform the following slicing operations:
    1. Extract elements from index 5 to 15 (exclusive)
    2. Extract every third element from the entire array
    3. Reverse the entire array using slicing
- Then, create a 2D array with shape (4, 5) containing integers from 0 to 19.
- Perform these slicing operations on the 2D array:
    1. Extract the second row
    2. Extract the third column
    3. Extract a 2x2 sub-array from the top-right corner

In [20]:
# Create the 1D array
array_1D = np.arange(20)
print("1D Array:", array_1D)

# Elements from index 5 to 15
slice_5_to_15 = array_1D[5:15]
print("Elements from index 5 to 15:", slice_5_to_15)

# Every third element
every_third_element = slice_5_to_15[::3]
print("Every third element:", every_third_element)

# Reverse the array
reversed_array = every_third_element[::-1]
print("Reversed Array:", reversed_array)

# Create a 2D array with shape (4, 5)
array_2d = array_1D.reshape(4, 5)
print("2D Array:\n", array_2d)

# The second row
second_row = array_2d[1, :]
print("Second row:", second_row)

# The third column
third_column = array_2d[:, 2]
print("Third column:", third_column)

# 2x2 sub-array from the top-right corner
sub_array = array_2d[:2, -2:]
print("2x2 Sub-array from the top-right corner:\n", sub_array)

1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Elements from index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14]
Every third element: [ 5  8 11 14]
Reversed Array: [14 11  8  5]
2D Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Second row: [5 6 7 8 9]
Third column: [ 2  7 12 17]
2x2 Sub-array from the top-right corner:
 [[3 4]
 [8 9]]


## NumPy Mathematical Operations

- Create a NumPy array of 10 random integers between 1 and 100.
- Perform the following operations:
    1. Calculate the square root of each element
    2. Find the absolute value of the difference between each element and the mean of the array
    3. Calculate e^x for each element x in the array
    4. Find the minimum and maximum values in the array
    5. Determine the sign (-1, 0, or 1) of the difference between each element and the median of the array
    6. Calculate the sine of each element
    7. Use np.log1p() to calculate log(1+x) for each element x

- For each operation, print the original array and the result. 
- Briefly explain the purpose of np.log1p() compared to np.log().

In [48]:
# Create the array
random_array = np.random.randint(1, 101, size=10)
print("Original Array:", random_array)
print()

# Calculate the square root of each element
sqrt_array = np.sqrt(random_array)
print("Original Array:", random_array)
print("Square Roots:", sqrt_array)
print()

# Find the absolute value of the difference between each element and the mean
mean_value = np.mean(random_array)
abs_diff_mean = np.abs(random_array - mean_value)
print("Original Array:", random_array)
print("Absolute Difference from Mean:", abs_diff_mean)
print()

# Calculate e^x
exp_array = np.exp(random_array)
print("Original Array:", random_array)
print("e^x for each element:", exp_array)
print()

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Original Array:", random_array)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print()

# Determine the sign (-1, 0, or 1) of the difference between each element and the median
median_value = np.median(random_array)
sign_diff_median = np.sign(random_array - median_value)
print("Original Array:", random_array)
print("Sign of Difference from Median:", sign_diff_median)
print()

# Calculate the sine
sine_array = np.sin(random_array)
print("Original Array:", random_array)
print("Sine of each element:", sine_array)
print()

# Use np.log1p() to calculate log(1+x)
log1p_array = np.log1p(random_array)
print("Original Array:", random_array)
print("log(1+x) for each element:", log1p_array)

# The purpose of np.log1p() versus np.log() is the numerical stability when x nears zero.
# For small values of x, log(1+x) is more accurate using np.log1p() than by calculating directly,
# due to how floting-point arithmetic is handled, avoiding loss of precision.

Original Array: [ 1 11 44 59 24 60  3 99 63 36]

Original Array: [ 1 11 44 59 24 60  3 99 63 36]
Square Roots: [1.         3.31662479 6.63324958 7.68114575 4.89897949 7.74596669
 1.73205081 9.94987437 7.93725393 6.        ]

Original Array: [ 1 11 44 59 24 60  3 99 63 36]
Absolute Difference from Mean: [39. 29.  4. 19. 16. 20. 37. 59. 23.  4.]

Original Array: [ 1 11 44 59 24 60  3 99 63 36]
e^x for each element: [2.71828183e+00 5.98741417e+04 1.28516001e+19 4.20121040e+25
 2.64891221e+10 1.14200739e+26 2.00855369e+01 9.88903032e+42
 2.29378316e+27 4.31123155e+15]

Original Array: [ 1 11 44 59 24 60  3 99 63 36]
Minimum Value: 1
Maximum Value: 99

Original Array: [ 1 11 44 59 24 60  3 99 63 36]
Sign of Difference from Median: [-1. -1.  1.  1. -1.  1. -1.  1.  1. -1.]

Original Array: [ 1 11 44 59 24 60  3 99 63 36]
Sine of each element: [ 0.84147098 -0.99999021  0.01770193  0.63673801 -0.90557836 -0.30481062
  0.14112001 -0.99920683  0.1673557  -0.99177885]

Original Array: [ 1 11 44 5